TOP=..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE
#=============================

# Note, the files in this directory were manually copied from the Fast CCD directories 
# for Linux and Windows.  The soft links for Linux were manually created.

INC += cin.h
LIB_INSTALLS_Linux += ../os/linux-x86_64/libcin.a

#=============================

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

