TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

LIBRARY_IOC_Linux += FastCCD
LIB_SRCS += FastCCD.cpp
LIB_SRCS += NDPluginFastCCD.cpp
LIB_LIBS += cin

DBD += FastCCDSupport.dbd

include $(ADCORE)/ADApp/commonLibraryMakefile

#=============================

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

